branches:
  only:
    - master
    - /^sentinel.+$/
    - /^acceptance_deploy.+$/
    - /^test_development-.*$/
    - /^\d+\.\d+\.\d+$/

os: linux

matrix:
  include:

# Web Jobs
########################################################################

#
# Job for building and deploying the web site
#
    - language: ruby
      rvm: 2.5.3
      sudo: false
      cache:
        bundle: true
        directories:
          - www/build
      env:
        - AFFECTED_FILES="support/ci/deploy_website.sh"
        - AFFECTED_DIRS="www"
        - AWS_BUCKET=habitat-www
        - AWS_DEFAULT_REGION=us-west-2
        - AWS_ACCESS_KEY_ID=AKIAJE6NFCK7ZR6TDVTQ
        # AWS_SECRET_ACCESS_KEY
        - secure: "HjOuNxDjf2BXnGqBBlrUdWJm56vb/ZbMKPT5STjtBuDAHIJy5D4UBaaT8yGOZL3TsRuC8MjHPLE5Pnn273fVghIjNoiUsxBf3sFIPuQylSMB4V4AvojVQiyVqgMyU82BN4qXXmOc7HD2fb3gfRVnBlkqu+lqJPwJPQx6x2H5X8SdyEMYhKxOxxI38e7KtVOHPLqBjbh0pnGTheRdCTa70jDIZpEbjD7OBOKjpLzVax/hfzTGyrHOVQkbMUWG9yNNY6CHW8sP3Lbbsa0Xg63xI/HODKDfjvfKXOSn9G08gwiS9R+8cZhtgXrKC19iLWp11mTVOhxMP0xptLGNRCrKTwknhHprP4E0xyoT79pDrNh0+fxmoY64yZ77pmZdYi1ikZxE1PI6KrFXwMsjke6TKmnSOtwrbKjl8keovosiU8Yu0zgPSpW5RDGuTk/xvb7Luyb7w39qxHzTA1FCgKXLbAIEPz4NUzV9CuPj658v+KM7iCNNRuhIZfdNwwE/tQeAHwf4Rs6x/2r46BpFy4i+Bcz1ZDf+iXlhFT5SK2GP2ql/cEevMICs4MMAg49MErFkbo1000Nbn8pf4h8ro2ZbZELRS5TDEEt6EpDU+r/R7vPc8+cmV37aQu3Rvznx53gEsUT6Wj4yC9poMwucahdUAk1FzY/45XwPuzTZ9Bp0X5E="
        # NETLIFYKEY
        - secure: "EyM8UThsqW8bFLzhUs/YeqDyGZh5dplgFkCs6Ps7hLx30BQArMy9PV8xVfvGfoWtLunw0TrBWd6vwmymF6Hf8Dv/p/qQgRD5m3OVSx50KJA7TTr42AhfKmfGfWaSQVYE8SayAiE+fPb4eHB85hekfpt2yawuRbUNyzCfmcic4sX+IIUBKHJih+6P+ovP9+aYXmo62VwEaLac0sOWB6n7wa57Y4vs/BIf4B3CjOUqAVpFxHdply+WcBCxuja3AQGyebofPpe7A+NdNoGgOSKiWgGL0ke7rW1/8r3icqQO0/MigOkvdZz8l/p19aeMcUR7NfDjTCKC8y4HbXIUltjHlatCiFPwjyqC9req/RTK7fYid7mOdQ6VEQD28oW0l4geEgwQltV6N/nsKmNX5JFvr7BhR3FKV3F7oA+bwUBBntxzPqkgSYOSwz4HnfZhTdJWtD0h1FYFU+rcHXw5JRTdoS0gA2wG22yXuROjOewPt0rIrrFHw8rj5T+457P55h33k4P+Ekx8W70TarSP0uweB646nGj62IHGXKrLS6VHwTeWxLwf9wdMx3c+JLrm4VPe0FHY642MlW2AERvDu9f48xGvwNUF9y+cIsGkghB1USYqs82tTW/oV9sAmRwoWPuBlT1mFf5RQe6HGXA/T7ThO/F7aKFWj8FZFG9BNNWDfq0="
        # FASTLY_API_KEY
        - secure: "a376gD8mJCV6hzzugodQf+qXgVeivn4ElB8yHEAygMu94//62KT37TDlsfzCvcf1yth8jnWaJpQ+zDMCgNvo7IBiTRDingGXu+uEOheDjPssYuhwLUiTjKMb2cEdU78oEGKEWMTK6IYPJ8U6D/Q+odRevbnlS1zdUvNyNTcW3+41G83ZxFGsJCU2we5cw0w7NigqZaEG0yD6S7WPxOb+qxcZJ5/UQ/OKEnb68iIvvCJV782BcWZzxSUAyilPuRmZkfGgSQ9TZUMiKdf0KEtJfisxEBZX1s46sxAz4OssyIDM/0tp/bBnKJStyGYJODo5O6/dy2EkFd7YWsRhRoCkf+HXMQiG4V//CpNwkmTVUpNVpjoELkkLqqxew/bIN897H6pb4D4n7cUm5OFl5N6V798u67DWfSXxSsuwIc+INFkAYWEAakLJj0xt0K5WULPG84PWSPuNkBY/tqj/2wOiuFsdXQqFhzATvQa4fBEOyNBMS3knd2ovmAxpRDabeH05chE2+PvzSmP+avBIaRPuqBM2XdMqxVWrKfVsXQ+/Tezo3KqMujv5Zo4HR1Jlo4Yqnm75gDDYu1U0J3PMSERxpr8IP7bYb3511Th5KH3/pRQLaVXOCOGWXPMHk8ofN7u2rRDvWAbG4to56M1ZuHhVrGhpOuMT2uYpIjm83qWyFa0="
        # FASTLY_SERVICE_KEY
        - secure: "nndTwXiUkVqtLaZ6ndFZHXKPoHvgCQmyJYpNHokgAA54cc8ART8F3ZZuka+fcM5a6dLUttB/rfvWm+Ytxi9XTpj0G2rAsR7+kBnWJf/FyfVi+r2YmYd7Bg9kGaDTigpYLgL+GUQxz3S2+QI/P1jzRDSRAz9LBVYIRnVyNVp8zYNcizD8HGopNfeFO3a2KIIEM4qvkQbwPVfHp9PmSLQfDPSStS6QBf1q2ebv94TzQz+xWozLQgY025KtY78YCXdj2930HJnbrrHiGfpvSAUSKjZcygLWXVSRKGkRTJJbenBXqK0uni4odpGmN+xL1afQlHfd+CBlXq6lyiZqoaRtIk2vkR8aGww5pouXBWA7UO4NMrqIk7nSzc1zpKgkNhiApr5O8xoy5dYSu6//tiRk63+jBSbZ7EoVPHqx2oBadykKJSlgeWzVGMSnEzad4fb2DDQKNVLObg0POZX/YdZKqbWv8DmiRkJkLKkE7iD5NYqpppl6OsCJDEBiKFbGokWi0YODOMkyTie9s9KQ3rZAIcnz4RjkYbj0F8S93BQ9Pefid3Yv20ix9OZQL1Cdf0HPBcE7fBWxfcWwbQVnoNrNIGsR3bbuqbuTuyiHT7E527QhOg12G4YZsrwoNZA6qGYZYg/4NNQTILFluTtG1YaZmWdN7vGXgiAYA4sDgGb9eiA="
      before_install: ./support/ci/fast_pass.sh || exit 0
      script: ./support/ci/deploy_website.sh


notifications:
  webhooks:
    urls:
      - http://bots.habitat.sh:4567/travis
    on_success: always
    on_failure: always
    on_start: always
  slack:
    template:
      - "%{repository} (%{commit}) : %{message}"
      - "Build details: %{build_url}"
      - "Status: %{result}"
    rooms:
      - secure: "uERbGr6e+5PdQLQdAhkElVg4NGmg0SCcFuebxcpFGKAbb5l5w5pYmmorNHdcDDpG4L+g3/wtTlRt9EiN2R1VYsJ/tLydrQF+9ZS7ERiYi7VhJRjZsVxOsNNz6VJNfypB7ZMq3t3zlwThWCqQyx6scvL9H1GEBWzd34Cm8+KA8t+37OfcTDU5UNWpblYx4HaSVsJygPQdGJM7SJ1nu9k7qkLsR2QNPKc9gJHbbhcUZQjjp6jFb1YMM1RWh6iK/GBxA2rTlqykmDiWBjQNDq6/G+jfPCuAVchMB2CBDH1SUYRfqOQ3A3/66seBnLif2m4q+cDJcjH2BggXkqu3MEGvNx8R8+d5dJnamS1T3G0zPax0kEQ3Uozsf/W+KEDTGylh57MqS/i8aIjKxlzPqia74S2d85IyP6hM8qgGzZUlcoRUXwNyaM1rj1K7uL8JHOq/3JHalQOV0qhq12pYKagSqwP/LV/+WvJE1U6aO39VnOGSzfN6ukxbfZAzP+dR6C08EJC137tcLEL4a32rEjK2C95vCw2Po02mXdatK7Sa0XI1hl5ZaQwm0nXycCcZDt1YYAotk3S5fCCe0Tsdw2gSxiOyXWalWC74WeMnP5vithZpReGIcwq4UvGlHx2/LEjP9azLhzTzDRQypaTMYVJFvcg6NccB4Z9gh5eNn1wWz90="
    on_pull_requests: false
    on_failure: always
    on_success: change
