# Documentation available at https://expeditor.chef.io/

github:
  # The file where the MAJOR.MINOR.PATCH version is kept. The version in this file
  # is bumped automatically via the `built_in:bump_version` merge_action.
  # TODO: Change this to `VERSION` once we are live
  version_file: "VERSION_FAKE"
  version_tag_format: 'fake-{{version}}'
  # The file where our CHANGELOG is kept. This file is updated automatically with
  # details from the Pull Request via the `built_in:update_changelog` merge_action.
  changelog_file: "CHANGELOG_FAKE.md"
  delete_branch_on_merge: true

# Slack channel in Chef Software slack to send notifications about Expeditor actions
slack:
  notify_channel: habitat-notify

changelog:
  categories:
    - "X-change": "Behavioral Changes"
    - "X-feature": "New Features & Enhancements"
    - "X-fix": "Bug Fixes"
  rollup_header: Changes not yet released to stable

pipelines:
  - verify:
      description: Pull Request validation tests
  - website:
      description: Deploy the website
      trigger: pull_request
  - release_habitat:
      description: Habitat release process
  - end_to_end:
      description: Habitat long running end to end tests - always runs on DEV environment

staging_areas:
  - post_merge:
      workload: pull_request_merged:{{agent_id}}:*

subscriptions:
  - workload: pull_request_opened:{{agent_id}}:*
    actions:
      - post_github_comment:.expeditor/templates/welcome.mustache

  - workload: staged_workload_released:{{agent_id}}:post_merge:*
    actions:
      - built_in:bump_version:
          ignore_labels:
          - 'Expeditor: Skip Version Bump'
          - 'Expeditor: Skip All'
      - built_in:update_changelog:
          ignore_labels:
          - 'Expeditor: Exclude from Changelog'
          - 'Expeditor: Skip All'
      - trigger_pipeline:release_habitat:
          only_if: built_in:bump_version
          post_commit: true

  - workload: buildkite_build_passed:{{agent_id}}:release_habitat:*
    actions:
      - trigger_pipeline:end_to_end:
          post_commit: true

  - workload: buildkite_build_passed:{{agent_id}}:end_to_end:*
    actions:
      - trigger_pipeline:test_scenarios:
          post_commit: true

  # Make sure we unlock to allow later builds if one fails.
  - workload: buildkite_build_failed:{{agent_id}}:release_habitat:*
    actions:
      - unlock_staging_area:post_merge:
          post_commit: true
          always_run: true

  - workload: buildkite_build_passed:{{agent_id}}:release_habitat:*
    actions:
      - unlock_staging_area:post_merge:
          post_commit: true
          always_run: true

  - workload: buildkite_build_canceled:{{agent_id}}:release_habitat:*
    actions:
      - unlock_staging_area:post_merge:
          post_commit: true
          always_run: true

  - workload: schedule_triggered:{{agent_id}}:cargo_update:*
    actions:
      - bash:.expeditor/scripts/cargo_update.sh

schedules:
  - name: cargo_update
    description: "Run 'cargo update' every Sunday at 2am"
    cronline: "0 2 * * 0"
